version: "3.8"

services:
  nest_api:
    image: ghcr.io/isaacbatst/felip-ai:${GIT_COMMIT_HASH:-latest}
    user: "1000:1000"
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public
    depends_on:
      - redis
    env_file:
      - envfile
    volumes:
      - /home/felip-ai/database:/app/nest_api/drizzle
      - /home/felip-ai/service-account-key.json:/app/nest_api/service-account-key.json:ro
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:8.4-alpine
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public
    volumes:
      - redis-data:/data
    command: >
      sh -c "
      mkdir -p /data/appendonlydir
      if [ -n \"$$REDIS_PASSWORD\" ]; then
        redis-server --requirepass $$REDIS_PASSWORD --appendonly yes --dir /data --appendfilename appendonlydir/appendonly.aof
      else
        redis-server --appendonly yes --dir /data --appendfilename appendonlydir/appendonly.aof
      fi
      "
    env_file:
      - envfile
    healthcheck:
      test: >
        sh -c "
        if [ -n \"$$REDIS_PASSWORD\" ]; then
          redis-cli -a $$REDIS_PASSWORD ping
        else
          redis-cli ping
        fi
        "
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local

networks:
  traefik-public:
    external: true

