services:
  nest_api:
    image: ghcr.io/isaacbatst/felip-ai:${GIT_COMMIT_HASH:-latest}
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nest-api.rule=Host(`chatbot.lfviagens.com`)"
        - "traefik.http.services.nest-api.loadbalancer.server.port=3000"
        - "traefik.http.routers.nest-api.entrypoints=websecure"
        - "traefik.http.routers.nest-api.tls.certresolver=myresolver"
        - "traefik.swarm.network=traefik-public"
    networks:
      - traefik-public
      - default
    env_file:
      - envfile
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
    volumes:
      - /home/felip-ai/service-account-key.json:/app/nest_api/service-account-key.json:ro
      - /home/felip-ai/.env-worker:/app/nest_api/.env-worker:ro
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: rabbitmq:4.2.3-management
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbitmq.rule=Host(`felip-queue.congressosimulator.com.br`)"
        - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
        - "traefik.http.routers.rabbitmq.entrypoints=websecure"
        - "traefik.http.routers.rabbitmq.tls.certresolver=myresolver"
        - "traefik.swarm.network=traefik-public"
    networks:
      - traefik-public
      - default
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    env_file:
      - envfile
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:5432:5432"
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-felip}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-felip}
      - POSTGRES_DB=${POSTGRES_DB:-felipdb}
    env_file:
      - envfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-felip} -d $${POSTGRES_DB:-felipdb}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq-data:
    driver: local
  postgres-data:
    driver: local

networks:
  traefik-public:
    external: true
  default:
    driver: overlay
